/**
 * F1 — Serializador .sop (TS-only)
 * Convierte el modelo del dashboard (VisualArtifact + Relationship) a texto SOL .sop
 * canónico: `Type:` por artefacto, `meta.id` en PascalCase, y referencias semánticas
 * `Type:Id` para las relaciones.
 *
 * Nota: versión enfocada del lado dashboard. En F0 se reemplaza por el serializador del
 * package `@hexy/sol`. Spec de referencias: ../../../docs/sol/SEMANTIC_REFERENCE_RULES.md
 */

import type { VisualArtifact, Relationship } from '../../types'

/** Deriva un id SOL canónico (`^[A-Z][a-zA-Z0-9]*$`) a partir del nombre del artefacto. */
export function idFromName(name: string): string {
    const ascii = (name ?? '').normalize('NFD').replace(/\p{Diacritic}/gu, '')
    const parts = ascii.split(/[^a-zA-Z0-9]+/).filter(Boolean)
    const pascal = parts.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('')
    if (!pascal) return 'Unnamed'
    return /^[A-Za-z]/.test(pascal) ? pascal : `A${pascal}`
}

/** Mapea el ArtifactType (lowercase) al keyword SOL en PascalCase (intent → Intent). */
export function solKeyword(type: string): string {
    if (!type) return 'Artifact'
    return type.charAt(0).toUpperCase() + type.slice(1)
}

const indentBlock = (text: string, indent: string): string =>
    text
        .trim()
        .split('\n')
        .map(line => `${indent}${line}`)
        .join('\n')

/**
 * Serializa artefactos + relaciones a un documento `.sop`.
 * Las relaciones cuyo target no resuelve a un artefacto se emiten con un id crudo, de modo
 * que el validador las marque como referencia colgante (anti-alucinación).
 */
export function serializeSop(artifacts: VisualArtifact[], relationships: Relationship[]): string {
    const byId = new Map(artifacts.map(a => [a.id, a]))
    const out: string[] = ['# Generated by Hexy Dashboard — SOL (.sop)', '']

    for (const a of artifacts) {
        const kw = solKeyword(a.type)
        const id = idFromName(a.name)
        const lines: string[] = [`${kw}:`, '  meta:', `    id: ${id}`, `    version: "${a.version ?? '1.0.0'}"`]

        if (a.description?.trim()) {
            lines.push('  description: >')
            lines.push(indentBlock(a.description, '    '))
        }

        const rels = relationships.filter(r => r.sourceId === a.id)
        if (rels.length > 0) {
            lines.push('  relationships:')
            for (const r of rels) {
                const target = byId.get(r.targetId)
                const ref = target ? `${solKeyword(target.type)}:${idFromName(target.name)}` : `Artifact:${r.targetId}`
                lines.push(`    - type: ${r.type}`)
                lines.push(`      target: ${ref}`)
            }
        }

        out.push(lines.join('\n'), '')
    }

    return out.join('\n')
}
